### ISSUE TITLE
How do you compile your BFS source code ?

### ISSUE THREAD

**Issue by senghuot** [nipunramk/Reducible#1]
I tried to compile your BFS src code via `manim bfs.py Introduction -pl` and got few errors. Do you use custom library instead of official ? how do you compile your changes ?

here are a few error example of errors I got (1) `DARK_BLUE_B` is not defined (2) geometry.py is not matching the official file in manimlib

```
  File "bfs.py", line 300, in highlight_node
    surround_circle = Circle(radius=node.circle.radius * scale_factor, start_angle=start_angle, TAU=-TAU)
  File "/usr/local/lib/python3.8/site-packages/manimlib/mobject/geometry.py", line 314, in __init__
    Arc.__init__(self, 0, TAU, **kwargs)
TypeError: __init__() got multiple values for argument 'start_angle'
```

**Comment by nipunramk** [comment]
Ah, yeah this is due to one hack I added to the manim source code to render animations for the graphs in a clockwise direction rather than a counter-clockwise direction, which I felt visually looked a little off. I did not include that code in this repo since I think for most use cases the official manim source code should not be modified. This was an exception I made with my intended use case. 

If you want to generate the same animations I did, you can modify manim's geometry.py Circle class with the following:

`
class Circle(Arc):
  | CONFIG = { |   | CONFIG = {
  | "color": RED, |   | "color": RED,
  | "close_new_points": True, |   | "close_new_points": True,
  | "anchors_span_full_range": False |   | "anchors_span_full_range": False
  | } |   | }
  |   |   |  
  | def __init__(self, **kwargs): |   | def __init__(self, start_angle=0, TAU=TAU, **kwargs):
  | Arc.__init__(self, 0, TAU, **kwargs) |   | Arc.__init__(self, start_angle, TAU, **kwargs)
  |   |  
`
What this allows you to do is now if you define and a start_angle and TAU=-TAU when initializing circles, they will be rendered in the clockwise direction from the starting angle provider, rather than the counter-clockwise direction from the default angle 0. There's probably a better way to do this, but this is a quick fix that I implemented. 

Also for the DARK_BLUE_B color, I added the following hex in the `COLOR_MAP` dictionary constant.py file. 
`"DARK_BLUE_B": "#120896"`

In general, most of the work in this repo does not modify the original manim library, but there are a few exceptions here and there. Colors are going to be one of them since defining custom colors in manim is quite easy.

Thanks for pointing this issue out, hope this helps.

**Comment by senghuot** [comment]
thank you, it works now with your help 👍
