### ISSUE TITLE
Beginners are having problems learning the author's source code

### ISSUE THREAD

**Issue by liujiangmu123** [nipunramk/Reducible#3]
Dear author, I am a beginner and have encountered a fundamental problem.  I have installed the latest version of the manimgl, then feel your work is very good, so I want to work began to learn from you, after I download your video source code, I found that my computer can't run, so, want to request you to see if I can make it to the one in the current version should be how to run your source code, although it is the foundation, but for beginners heartfelt thanks to you.
This is the file structure after I opened it and a lot of errors. At this point, I have installed the latest version of Manimgl on my computer python
![baogao](https://user-images.githubusercontent.com/94793556/142767140-eaabe0c3-c467-4763-b545-71bbca97a82f.png)

**Comment by nipunramk** [comment]
Hi, first off, thanks for bringing this up. Just so you are aware, the older projects in this repository (everything up until Huffman codes) used a version of Manim that was built on top of Cairo (see https://docs.manim.community/en/stable/installation/versions.html for more about different versions of manim). As a beginner, I highly recommend starting with Manim Community Edition (https://docs.manim.community/en/stable/index.html). It is well documented and much more intuitive to use for beginners than ManimGL (at least in my opinion). 

In terms of fixing this problem, it's probably not easily fixable since there are so many differences between ManimGL and the older Manim Cairo versions. The best way to learn from my examples if you would like to is work with smaller scenes one at a time and really pick apart how they work in terms of the logic. But as mentioned, the best way to learn is using ManimCE. If you want to see a larger project that uses ManimCE, a good example is in 2021/MarchingSquares/scene.py.

**Comment by liujiangmu123** [comment]
Thank you very much, dear author,, I like your YouTube works very much, thank you for your efforts

**Comment by liujiangmu123** [comment]
Dear author, first of all thank you for taking the time to answer my questions. I installed this version of Cairo and wanted to run all your codes on my computer again, but it was still unsuccessful. If I want your code to be in my The computer is running, what should I do? Dear author, I think that getting the code to run should be the first step in learning, so how can I run your code in my computer, learn module by module

**Comment by nipunramk** [comment]
Unfortunately, without more details on the errors you are seeing, there's not much I can really do here to help. Some projects in this repo (especially the early 2020 ones) use a really old version of manim that may not be well supported. I mostly put this code here for people to use as an example for how to do specific things with manim. 

If you are a beginner with manim, I would recommend not to try digest an entire project at once, but take smaller examples from a project (such as a single scene that interests you) and see if you can modify and get it working for you.  Trying to understand a project that has many lines of code and has many errors on your development environment will most probably not be a productive use of your time. Start with small examples, and that way, the errors you see will also be much more isolated and easier to debug.

**Comment by liujiangmu123** [comment]
Thank you very much, I can understand what you mean, I divided it into a small example, this is really a very good suggestion, I gained a lot, the code can also be completed through my own modification
